fixes for aws

diff --git a/esp-cloud/bin/aws-get-images b/esp-cloud/bin/aws-get-images
--- a/esp-cloud/bin/aws-get-images
+++ b/esp-cloud/bin/aws-get-images
@@ -5,20 +5,18 @@
 ROOT=`dirname $0`
 ROOT=`readlink -f $ROOT`
 
-az account show &>/dev/null ; [ 0 -ne $? ] && echo "not logged in to azure" && exit 1
-
 # usage 
 #
 show_usage() {
     echo "Usage: $0"
     echo ""
-    echo "required: -r <geographical location>"
+    echo "required: -g <geographical location>"
     echo ""
     echo "optional: -p <registry prefix>"
     exit 1
 }   
 
-while getopts "?p:r:" opt; do
+while getopts "?p:g:" opt; do
     case "$opt" in
         \?)
             show_usage
@@ -26,21 +24,22 @@ while getopts "?p:r:" opt; do
             ;;
 	p)  BUILD_LEVEL=$OPTARG/
 	    ;;
-	r)  AWS_RG=$OPTARG
+	g)  AWS_LO=$OPTARG
 	    ;;
         *)
             echo "bad option <$opt>" && show_usage
     esac
 done
 
-aws sts get-caller-identity &>/dev/null ; [ 0 -ne $? ] && echo "not logged in to AWS" && exit 1
+[ -z $AWS_LO ] && echo "region EKS cluster resides in must be specified" && show_usage
 
-[ -z $AWS_RG ] && echo "region EKS cluster resides in must be specified" && show_usage
+az account show &>/dev/null ; [ 0 -ne $? ] && echo "not logged in to azure" && exit 1
+aws configure set region ${AWS_LO}
 
 AWS_ACCID=$(aws sts get-caller-identity | jq '.Account')
 [ 0 -ne $? ] && echo "could not obtain AWS Account ID" && exit 1
 AWS_ACCID=$(eval echo $AWS_ACCID)
-AWS_CRLS=$AWS_ACCID.dkr.ecr.$AWS_RG.amazonaws.com
+AWS_CRLS=$AWS_ACCID.dkr.ecr.$AWS_LO.amazonaws.com
 
 get_latest_version() {
     local REPO=$1
diff --git a/esp-cloud/bin/aws-push b/esp-cloud/bin/aws-push
--- a/esp-cloud/bin/aws-push
+++ b/esp-cloud/bin/aws-push
@@ -5,38 +5,39 @@
 ROOT=`dirname $0`
 ROOT=`readlink -f $ROOT`
 
-aws sts get-caller-identity &>/dev/null ; [ 0 -ne $? ] && echo "not logged in to AWS" && exit 1
-
 # usage 
 #
 show_usage() {
     echo "Usage: $0"
     echo ""
-    echo "required: -r <EKS geographical region>"
+    echo "required: -g <EKS geographical region>"
     exit 1
 }   
 
-while getopts "?r:" opt; do
+while getopts "?g:" opt; do
     case "$opt" in
         \?)
             show_usage
             return 1
             ;;
-	r)  AWS_REG=$OPTARG
+	g)  AWS_LO=$OPTARG
 	    ;;
         *)
             echo "bad option <$opt>" && show_usage
     esac
 done
 
-[ -z $AWS_REG ] && echo "region EKS cluster resides in must be specified" && show_usage
+[ -z $AWS_LO ] && echo "region EKS cluster resides in must be specified" && show_usage
+
+aws sts get-caller-identity &>/dev/null ; [ 0 -ne $? ] && echo "not logged in to AWS" && exit 1
+aws configure set region ${AWS_LO}
 
 AWS_ACCID=`aws sts get-caller-identity | jq '.Account'`
 [ 0 -ne $? ] && echo "could not obtain AWS Account ID" && exit 1
 AWS_ACCID=`eval echo $AWS_ACCID`
 
-AWS_CRLS=$AWS_ACCID.dkr.ecr.$AWS_REG.amazonaws.com
-aws ecr get-login-password --region $AWS_REG | docker login --username AWS --password-stdin $AWS_CRLS
+AWS_CRLS=$AWS_ACCID.dkr.ecr.$AWS_LO.amazonaws.com
+aws ecr get-login-password | docker login --username AWS --password-stdin $AWS_CRLS
 [ 0 -ne $? ] && echo "could not login to AWS docker registry" && exit 1
 
 
@@ -68,9 +69,9 @@ for i in `env| fgrep IMAGE_ | fgrep repulp`; do
     docker pull $IMAGE &> /dev/null
     [ 0 -ne $? ] && echo "failed" && exit 0 
 
-    aws ecr describe-repositories --region $AWS_REG | jq '.[] | .[].repositoryName' | fgrep "$BUILD_LEVEL$AWS_REPO"
+    aws ecr describe-repositories | jq '.[] | .[].repositoryName' | fgrep "$BUILD_LEVEL$AWS_REPO"
     if [ 0 -ne $? ]; then
-	aws ecr create-repository --region $AWS_REG --repository-name "$BUILD_LEVEL$AWS_REPO" &>/dev/null
+	aws ecr create-repository --repository-name "$BUILD_LEVEL$AWS_REPO" &>/dev/null
     fi
     echo "   docker tag"
     docker tag $IMAGE $AWS_CRLS/${BUILD_LEVEL}$AWS_REPO:$TAG    
@@ -90,4 +91,4 @@ done
 
 echo "export IMAGE_UAA=ghcr.io/skolodzieski/uaa:74.29.0" >> $ROOT/aws-images
 
-. $ROOT/azure-images
+. $ROOT/aws-images
diff --git a/esp-cloud/bin/aws-teardown b/esp-cloud/bin/aws-teardown
--- a/esp-cloud/bin/aws-teardown
+++ b/esp-cloud/bin/aws-teardown
@@ -12,12 +12,12 @@ aws sts get-caller-identity &>/dev/null ; [ 0 -ne $? ] && echo "not logged in to
 show_usage() {
     echo "Usage: $0"
     echo ""
-    echo "required: -c <cluster name> -r <geographical region>"
+    echo "required: -c <cluster name> -g <geographical region>"
     echo ""
     exit 1
 }   
 
-while getopts "?c:r:" opt; do
+while getopts "?c:g:" opt; do
     case "$opt" in
         \?)
             show_usage
@@ -25,7 +25,7 @@ while getopts "?c:r:" opt; do
             ;;
 	c)  AWS_CL=$OPTARG
 	    ;;
-	r)  AWS_RG=$OPTARG
+	g)  AWS_LO=$OPTARG
 	    ;;	
         *)
             echo "bad option <$opt>" && show_usage
@@ -33,7 +33,10 @@ while getopts "?c:r:" opt; do
 done
 
 [ -z $AWS_CL ]       && echo "cluster name must be specified" && show_usage
-[ -z $AWS_RG ]       && echo "cluster region must be specified" && show_usage
+[ -z $AWS_LO ]       && echo "cluster region must be specified" && show_usage
+
+az account show &>/dev/null ; [ 0 -ne $? ] && echo "not logged in to azure" && exit 1
+aws configure set region ${AWS_LO}
 
 # Getting EFS
 #
@@ -58,4 +61,4 @@ done
 #
 echo "deleting EFS($AWS_FS) from cluster"
 aws efs delete-file-system --file-system-id ${AWS_FS}
-eksctl delete cluster --region ${AWS_RG} --name=${AWS_CL}
+eksctl delete cluster --name=${AWS_CL}
diff --git a/esp-cloud/bin/aws-tennant b/esp-cloud/bin/aws-tennant
--- a/esp-cloud/bin/aws-tennant
+++ b/esp-cloud/bin/aws-tennant
@@ -5,19 +5,17 @@
 ROOT=`dirname $0`
 ROOT=`readlink -f $ROOT`
 
-aws sts get-caller-identity &>/dev/null ; [ 0 -ne $? ] && echo "not logged in to AWS" && exit 1
-
 # usage 
 #
 show_usage() {
     echo "Usage: $0"
     echo ""
-    echo "required: -c <cluster name> -t <tennant name>"
+    echo "required: -c <cluster name> -t <tennant name> -g <geographical location>"
     echo ""
     exit 1
 }   
 
-while getopts "?c:t:" opt; do
+while getopts "?c:t:g:" opt; do
     case "$opt" in
         \?)
             show_usage
@@ -27,6 +25,8 @@ while getopts "?c:t:" opt; do
 	    ;;
 	t)  AWS_NS=$OPTARG
 	    ;;
+	g)  AWS_LO=$OPTARG
+	    ;;
         *)
             echo "bad option <$opt>" && show_usage
     esac
@@ -34,6 +34,11 @@ done
 
 [ -z $AWS_CL ]       && echo "cluster name must be specified" && show_usage
 [ -z $AWS_NS ]       && echo "K8 namespace must be specified" && show_usage
+[ -z $AWS_LO ]       && echo "region EKS cluster resides in must be specified" && show_usage
+
+aws sts get-caller-identity &>/dev/null ; [ 0 -ne $? ] && echo "not logged in to AWS" && exit 1
+aws configure set region ${AWS_LO}
+
 
 echo "creating K8 namespace"
 kubectl get ns/$AWS_NS &> /dev/null
