refactor: new pv for postgres, dynamic PV, no NS PV scoping, yml --> yaml

diff --git a/esp-cloud/bin/dodeploy b/esp-cloud/bin/dodeploy
--- a/esp-cloud/bin/dodeploy
+++ b/esp-cloud/bin/dodeploy
@@ -101,6 +101,34 @@ if [ -f $DEPLOYMENT/pvc.yaml ] ; then
     fi
 fi
 
+# apply pcv-pg.yaml
+if [ -f $DEPLOYMENT/pvc-pg.yaml ] ; then
+    kubectl -n ${ESP_NS} apply -f $DEPLOYMENT/pvc-pg.yaml
+    i=0;
+    OK="n"
+    echo ""
+    while [[ i -le 10 ]] ;
+    do
+        echo -n "."
+        sleep 2;
+	kubectl -n ${ESP_NS} get pvc/esp-pv-pg | fgrep -i bound &>/dev/null	
+        if [ $? -eq 0 ]; then
+	    OK="y"
+            echo ""
+            echo "  The Persitent Volume has been sucessfully bound!"
+	    break;
+        fi
+        i=$((i+1));
+    done;
+    echo ""
+    if [[ "n" = "$OK" ]] ; then
+	echo "  After 10 iteration, Persitent Volume Claim remains unbound"
+	echo "     aborting deployment"
+	exit 1
+    fi
+fi
+
+
 # apply postgres.yaml
 #
 if [ -f $DEPLOYMENT/postgres.yaml ] ; then
@@ -131,7 +159,7 @@ fi
 
 # Apply non _crd.yaml files
 #
-LIST=`find ${DEPLOYMENT} -type f \( -iname "*.y*ml" ! -iwholename "*project/*" ! -iwholename "*examples/*" ! -iname "pvc.yaml" ! -iname "postgres.yaml" ! -iname "*_crd.y*ml" \)`
+LIST=`find ${DEPLOYMENT} -type f \( -iname "*.y*ml" ! -iwholename "*project/*" ! -iwholename "*examples/*" ! -iname "pvc.yaml" ! -iname "pvc-pg.yaml" ! -iname "postgres.yaml" ! -iname "*_crd.y*ml" \)`
 for i in ${LIST} ; do
     echo "deploying: $i"
     kubectl -n ${ESP_NS} apply -f $i
