Support for Kubernetes 1.22

diff --git a/esp-cloud/bin/dodeploy b/esp-cloud/bin/dodeploy
--- a/esp-cloud/bin/dodeploy
+++ b/esp-cloud/bin/dodeploy
@@ -78,13 +78,20 @@ fi
 
 . $ROOT/bin/mksecrets
 
-# Apply _crd.yaml files -- these are not namespace scoped. 
 #
-LIST=`find ${DEPLOYMENT} -type f \( -iname "*_crd.y*ml" ! -iwholename "*project/*" ! -iwholename "*examples/*" \)`
-for i in ${LIST} ; do
-    echo "deploying: $i"
-    kubectl apply -f $i
-done
+# Apply K8s CRD resources.
+#
+while read -r -s i
+do
+    echo "Applying: '${i}'"
+    kubectl apply -f "${i}" --dry-run=server || {
+        # The dry run failed.
+        # Kubectl should have displayed an error.
+        echo >&2 $'\n'"Kubectl failed to apply the '${i}' custom resource definitions."
+        exit 1
+    }
+    kubectl apply -f "${i}"
+done < <(find "${DEPLOYMENT}/operator/crds/" -type f -iname '*.y?ml')
 
 # apply pcv.yaml
 if [ -f $DEPLOYMENT/pvc.yaml ] ; then
@@ -125,10 +132,11 @@ if [ -f $DEPLOYMENT/postgres.yaml ] ; then
     fi
 fi    
 
-# Apply non _crd.yaml files
 #
-LIST=`find ${DEPLOYMENT} -type f \( -iname "*.y*ml" ! -iwholename "*project/*" ! -iwholename "*examples/*" ! -iname "pvc.yaml" ! -iname "pvc-pg.yaml" ! -iname "postgres.yaml" ! -iname "*_crd.y*ml" \)`
-for i in ${LIST} ; do
+# Apply K8s non-CRD resources.
+#
+while read -r -s i
+do
     echo "deploying: $i"
     kubectl -n ${ESP_NS} apply -f $i
-done
+done < <(find "${DEPLOYMENT}" -wholename "${DEPLOYMENT}/operator/crds" -prune -o -type f \( -iname "*.y*ml" ! -iwholename "*project/*" ! -iwholename "*examples/*" ! -iname "pvc.yaml" ! -iname "pvc-pg.yaml" ! -iname "postgres.yaml" \))
diff --git a/esp-cloud/bin/get-images b/esp-cloud/bin/get-images
--- a/esp-cloud/bin/get-images
+++ b/esp-cloud/bin/get-images
@@ -1,8 +1,20 @@
+#!/usr/bin/env sh
+
 #  Copyright © 2019, SAS Institute Inc., Cary, NC, USA.  All Rights Reserved.
 #  SPDX-License-Identifier: Apache-2.0
 
 getTag3() {
-    curl -X GET -s -k https://repulpmaster.unx.sas.com/v2/${1}/${2}/tags/list | jq '.tags' | tr -d '", ' | tr -d ',' | head -n -1 | tail -n +1 | sort -t '-' -k 2 | tail -1
+    if test -z "${1:-}"; then
+        echo >&2 'Missing container image repository.'
+        return 1
+    fi
+    if test -z "${2:-}"; then
+        echo >&2 'Missing container image name.'
+        return 1
+    fi
+    _url="https://repulpmaster.unx.sas.com/v2/${1}/${2}/tags/list"
+    curl -s -k "${_url}" | jq -r '[.tags[] | [gsub("[-]";".") | split(".")[] | ("0"*(8-(.|length)))[0:8]+.] | join(".")] | sort | reverse | .[0] | [split(".")[] | tonumber] | join(".")' | sed -e 's/\./-/3'
+    unset _url
 }
 
 getImages() {
@@ -51,7 +63,7 @@ show_usage() {
 }   
 
 
-BUILD_LEVEL=""
+BUILD_LEVEL="snapshot"
 [ "$1" == "-R" ] && BUILD_LEVEL=release
 [ "$1" == "-S" ] && BUILD_LEVEL=snapshot
 
