fix aws-get-images, add gcp-get-images

diff --git a/esp-cloud/bin/gcp-get-images b/esp-cloud/bin/gcp-get-images
--- a/esp-cloud/bin/gcp-get-images
+++ b/esp-cloud/bin/gcp-get-images
@@ -10,46 +10,42 @@ ROOT=`readlink -f $ROOT`
 show_usage() {
     echo "Usage: $0"
     echo ""
-    echo "required: -g <geographical location>"
+    echo "required: -P <Google Project>"
     echo ""
     echo "optional: -p <registry prefix>"
     exit 1
 }   
 
-while getopts "?p:g:" opt; do
+while getopts "?p:P:" opt; do
     case "$opt" in
         \?)
             show_usage
             return 1
             ;;
-	p)  BUILD_LEVEL=$OPTARG/
+	p)  GCP_PR=$OPTARG
 	    ;;
-	g)  AWS_LO=$OPTARG
+	P)  BUILD_LEVEL=$OPTARG/
 	    ;;
         *)
             echo "bad option <$opt>" && show_usage
     esac
 done
 
-[ -z $AWS_LO ] && echo "region EKS cluster resides in must be specified" && show_usage
+[ -z $GCP_PR ]       && echo "GCP project (subscription) must be specified" && show_usage
 
-aws sts get-caller-identity &>/dev/null ; [ 0 -ne $? ] && echo "not logged in to AWS" && exit 1
-aws configure set region ${AWS_LO}
+gcloud organizations list &> /dev/null ; [ 0 -ne $? ] && echo "not logged in to GCP" && exit 1
 
-AWS_ACCID=$(aws sts get-caller-identity | jq '.Account')
-[ 0 -ne $? ] && echo "could not obtain AWS Account ID" && exit 1
-AWS_ACCID=$(eval echo $AWS_ACCID)
-AWS_CRLS=$AWS_ACCID.dkr.ecr.$AWS_LO.amazonaws.com
+GCP_CRLS=gcr.io/${GCP_PR}
 
 get_latest_version() {
     local REPO=$1
-    local TAG=$(aws ecr describe-images --repository-name ${REPO}  --query 'sort_by(imageDetails,& imagePushedAt)[-1].imageTags[0]' --output text)
+    local TAG=$(eval echo $(gcloud container images list-tags ${GCP_CRLS}/${REPO} --limit=1 --format=json | jq .[0].tags[0]))
     echo ${REPO}:${TAG}
 }
 
 get_image() {
     local LV=`get_latest_version $2`
-    FOO=$AWS_CRLS/$LV
+    FOO=$GCP_CRLS/$LV
     echo "export $1=$FOO"
 }
 
